"""Add user relationship to resume and move user fields

Revision ID: d8e67a3e8339
Revises:
Create Date: 2025-06-09 11:34:15.345974

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d8e67a3e8339"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.drop_column("phone")
        batch_op.drop_column("name")
        batch_op.drop_column("website")
        batch_op.drop_column("linkedin")
        batch_op.drop_column("github")
        batch_op.drop_column("email")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("phone", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("linkedin", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("github", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("website", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("website")
        batch_op.drop_column("github")
        batch_op.drop_column("linkedin")
        batch_op.drop_column("phone")

    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("github", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("linkedin", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("website", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
