name: Texify CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'texify/**'
  pull_request:
    branches:
      - main
    paths:
      - 'texify/**'

jobs:
  lint:
    name: Lint Texify with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff on texify/
        run: ruff format --check texify/
